### ISSUE TITLE
[feature request] Don’t trigger when pressing a combination key, only trigger under a single specified modifier key

### ISSUE THREAD

**Issue by eret9616** [Keyruu/tabula#1]
I use the Command key as a combination key because several other optional modifier keys are being used by other software, and I can’t use them anymore. However, many shortcuts require the Command key, and I often accidentally trigger it unintentionally. I hope it can be set to only trigger when pressing this key alone.

**Comment by Keyruu** [comment]
Hey, thank you for using my tool! 

That should be possible. I'll take a look after work and get back to you.

**Comment by Keyruu** [comment]
This is implemented in [1.4.0](https://github.com/Keyruu/tabula/releases/tag/1.4.0).

I did notice a bug with using command as the modifier. You can read about that issue here: #2.
