### ISSUE TITLE
[feature request]Increase the key press trigger delay time

### ISSUE THREAD

**Issue by eret9616** [Keyruu/tabula#3]
Similar to Karabiner Elements’ to_if_alone_timeout_milliseconds, the key could be triggered after a certain delay when pressed to prevent accidental triggers and other potential issues

**Comment by Keyruu** [comment]
Yeah, I like that idea. Do you think a step size of the configurable delay of 100 ms is good enough? Or would you like to be able to set a very specific delay? Like 333 ms and 567 ms or would just be 300 ms and 600 ms be okay?

**Comment by Keyruu** [comment]
Implemented in [1.5.0](https://github.com/Keyruu/tabula/releases/tag/1.5.0). 

I went with the step size of 100. If it is really needed to have a very specific delay, I will revisit this, but I really don't think you need it that specific.
